name: Project CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subdir: [web-app, machine-learning-client]

    defaults:
      run:
        working-directory: ${{ matrix.subdir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv sync --dev

      - name: Run tests with Pytest
        run: pipenv run pytest --cov=. --cov-report=term-missing
      
      - name: Enforce 80% test coverage
        run: |
          COVERAGE=$(pipenv run coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Test coverage is below 80%" >&2
            exit 1
          fi
